// Code generated by MockGen. DO NOT EDIT.
// Source: slack.go
//
// Generated by this command:
//
//	mockgen --source=slack.go --destination=mock/mock.go --package mock_slack
//

// Package mock_slack is a generated GoMock package.
package mock_slack

import (
	context "context"
	reflect "reflect"

	slack "github.com/Flashgap/marvin/internal/service/slack"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetUser mocks base method.
func (m *MockService) GetUser(ctx context.Context, userID string) (*slack.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, userID)
	ret0, _ := ret[0].(*slack.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockServiceMockRecorder) GetUser(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockService)(nil).GetUser), ctx, userID)
}

// SendDM mocks base method.
func (m *MockService) SendDM(ctx context.Context, userID, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendDM", ctx, userID, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendDM indicates an expected call of SendDM.
func (mr *MockServiceMockRecorder) SendDM(ctx, userID, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDM", reflect.TypeOf((*MockService)(nil).SendDM), ctx, userID, message)
}
