// Code generated by MockGen. DO NOT EDIT.
// Source: github.go
//
// Generated by this command:
//
//	mockgen --source=github.go --destination=mock/mock.go --package mock_github
//

// Package mock_github is a generated GoMock package.
package mock_github

import (
	context "context"
	reflect "reflect"

	github "github.com/Flashgap/marvin/pkg/github"
	github0 "github.com/google/go-github/v63/github"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AddAssignees mocks base method.
func (m *MockClient) AddAssignees(ctx context.Context, webhook github.RepoSenderGetter, prNumber int, assignees []string) (*github0.Issue, *github0.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAssignees", ctx, webhook, prNumber, assignees)
	ret0, _ := ret[0].(*github0.Issue)
	ret1, _ := ret[1].(*github0.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AddAssignees indicates an expected call of AddAssignees.
func (mr *MockClientMockRecorder) AddAssignees(ctx, webhook, prNumber, assignees any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAssignees", reflect.TypeOf((*MockClient)(nil).AddAssignees), ctx, webhook, prNumber, assignees)
}

// AddPRLabels mocks base method.
func (m *MockClient) AddPRLabels(ctx context.Context, webhook github.RepoSenderGetter, prNumber int, labels []string) ([]*github0.Label, *github0.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPRLabels", ctx, webhook, prNumber, labels)
	ret0, _ := ret[0].([]*github0.Label)
	ret1, _ := ret[1].(*github0.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AddPRLabels indicates an expected call of AddPRLabels.
func (mr *MockClientMockRecorder) AddPRLabels(ctx, webhook, prNumber, labels any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPRLabels", reflect.TypeOf((*MockClient)(nil).AddPRLabels), ctx, webhook, prNumber, labels)
}

// CreateCheckRun mocks base method.
func (m *MockClient) CreateCheckRun(ctx context.Context, webhook github.RepoSenderGetter, opts github0.CreateCheckRunOptions) (*github0.CheckRun, *github0.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCheckRun", ctx, webhook, opts)
	ret0, _ := ret[0].(*github0.CheckRun)
	ret1, _ := ret[1].(*github0.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateCheckRun indicates an expected call of CreateCheckRun.
func (mr *MockClientMockRecorder) CreateCheckRun(ctx, webhook, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCheckRun", reflect.TypeOf((*MockClient)(nil).CreateCheckRun), ctx, webhook, opts)
}

// CreatePRComment mocks base method.
func (m *MockClient) CreatePRComment(ctx context.Context, webhook github.RepoSenderGetter, prNumber int, body *github0.IssueComment) (*github0.IssueComment, *github0.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePRComment", ctx, webhook, prNumber, body)
	ret0, _ := ret[0].(*github0.IssueComment)
	ret1, _ := ret[1].(*github0.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreatePRComment indicates an expected call of CreatePRComment.
func (mr *MockClientMockRecorder) CreatePRComment(ctx, webhook, prNumber, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePRComment", reflect.TypeOf((*MockClient)(nil).CreatePRComment), ctx, webhook, prNumber, body)
}

// EditPR mocks base method.
func (m *MockClient) EditPR(ctx context.Context, webhook github.RepoSenderGetter, prNumber int, body *github0.PullRequest) (*github0.PullRequest, *github0.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditPR", ctx, webhook, prNumber, body)
	ret0, _ := ret[0].(*github0.PullRequest)
	ret1, _ := ret[1].(*github0.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// EditPR indicates an expected call of EditPR.
func (mr *MockClientMockRecorder) EditPR(ctx, webhook, prNumber, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditPR", reflect.TypeOf((*MockClient)(nil).EditPR), ctx, webhook, prNumber, body)
}

// GetBranchProtection mocks base method.
func (m *MockClient) GetBranchProtection(ctx context.Context, webhook github.RepoSenderGetter, branch string) (*github0.Protection, *github0.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBranchProtection", ctx, webhook, branch)
	ret0, _ := ret[0].(*github0.Protection)
	ret1, _ := ret[1].(*github0.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetBranchProtection indicates an expected call of GetBranchProtection.
func (mr *MockClientMockRecorder) GetBranchProtection(ctx, webhook, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBranchProtection", reflect.TypeOf((*MockClient)(nil).GetBranchProtection), ctx, webhook, branch)
}

// GetCommit mocks base method.
func (m *MockClient) GetCommit(ctx context.Context, webhook github.RepoSenderGetter, sha string, opts *github0.ListOptions) (*github0.RepositoryCommit, *github0.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommit", ctx, webhook, sha, opts)
	ret0, _ := ret[0].(*github0.RepositoryCommit)
	ret1, _ := ret[1].(*github0.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetCommit indicates an expected call of GetCommit.
func (mr *MockClientMockRecorder) GetCommit(ctx, webhook, sha, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommit", reflect.TypeOf((*MockClient)(nil).GetCommit), ctx, webhook, sha, opts)
}

// ListCheckRunsForRef mocks base method.
func (m *MockClient) ListCheckRunsForRef(ctx context.Context, webhook github.RepoSenderGetter, ref string, opts *github0.ListCheckRunsOptions) (*github0.ListCheckRunsResults, *github0.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCheckRunsForRef", ctx, webhook, ref, opts)
	ret0, _ := ret[0].(*github0.ListCheckRunsResults)
	ret1, _ := ret[1].(*github0.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListCheckRunsForRef indicates an expected call of ListCheckRunsForRef.
func (mr *MockClientMockRecorder) ListCheckRunsForRef(ctx, webhook, ref, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCheckRunsForRef", reflect.TypeOf((*MockClient)(nil).ListCheckRunsForRef), ctx, webhook, ref, opts)
}

// ListCheckSuites mocks base method.
func (m *MockClient) ListCheckSuites(ctx context.Context, prEvent *github0.PullRequestEvent, opts *github0.ListCheckSuiteOptions) (*github0.ListCheckSuiteResults, *github0.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCheckSuites", ctx, prEvent, opts)
	ret0, _ := ret[0].(*github0.ListCheckSuiteResults)
	ret1, _ := ret[1].(*github0.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListCheckSuites indicates an expected call of ListCheckSuites.
func (mr *MockClientMockRecorder) ListCheckSuites(ctx, prEvent, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCheckSuites", reflect.TypeOf((*MockClient)(nil).ListCheckSuites), ctx, prEvent, opts)
}

// ListLabels mocks base method.
func (m *MockClient) ListLabels(ctx context.Context, webhook github.RepoSenderGetter, opts *github0.ListOptions) ([]*github0.Label, *github0.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListLabels", ctx, webhook, opts)
	ret0, _ := ret[0].([]*github0.Label)
	ret1, _ := ret[1].(*github0.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListLabels indicates an expected call of ListLabels.
func (mr *MockClientMockRecorder) ListLabels(ctx, webhook, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListLabels", reflect.TypeOf((*MockClient)(nil).ListLabels), ctx, webhook, opts)
}

// ListPR mocks base method.
func (m *MockClient) ListPR(ctx context.Context, webhook github.RepoSenderGetter, opts *github0.PullRequestListOptions) ([]*github0.PullRequest, *github0.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPR", ctx, webhook, opts)
	ret0, _ := ret[0].([]*github0.PullRequest)
	ret1, _ := ret[1].(*github0.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPR indicates an expected call of ListPR.
func (mr *MockClientMockRecorder) ListPR(ctx, webhook, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPR", reflect.TypeOf((*MockClient)(nil).ListPR), ctx, webhook, opts)
}

// ListPRCommits mocks base method.
func (m *MockClient) ListPRCommits(ctx context.Context, webhook github.RepoSenderGetter, prNumber int, opts *github0.ListOptions) ([]*github0.RepositoryCommit, *github0.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPRCommits", ctx, webhook, prNumber, opts)
	ret0, _ := ret[0].([]*github0.RepositoryCommit)
	ret1, _ := ret[1].(*github0.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPRCommits indicates an expected call of ListPRCommits.
func (mr *MockClientMockRecorder) ListPRCommits(ctx, webhook, prNumber, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPRCommits", reflect.TypeOf((*MockClient)(nil).ListPRCommits), ctx, webhook, prNumber, opts)
}

// ListPRFiles mocks base method.
func (m *MockClient) ListPRFiles(ctx context.Context, webhook github.RepoSenderGetter, prNumber int, opts *github0.ListOptions) ([]*github0.CommitFile, *github0.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPRFiles", ctx, webhook, prNumber, opts)
	ret0, _ := ret[0].([]*github0.CommitFile)
	ret1, _ := ret[1].(*github0.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListPRFiles indicates an expected call of ListPRFiles.
func (mr *MockClientMockRecorder) ListPRFiles(ctx, webhook, prNumber, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPRFiles", reflect.TypeOf((*MockClient)(nil).ListPRFiles), ctx, webhook, prNumber, opts)
}

// ListReviewers mocks base method.
func (m *MockClient) ListReviewers(ctx context.Context, webhook github.RepoSenderGetter, number int, opts *github0.ListOptions) (*github0.Reviewers, *github0.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReviewers", ctx, webhook, number, opts)
	ret0, _ := ret[0].(*github0.Reviewers)
	ret1, _ := ret[1].(*github0.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListReviewers indicates an expected call of ListReviewers.
func (mr *MockClientMockRecorder) ListReviewers(ctx, webhook, number, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReviewers", reflect.TypeOf((*MockClient)(nil).ListReviewers), ctx, webhook, number, opts)
}

// ListReviews mocks base method.
func (m *MockClient) ListReviews(ctx context.Context, webhook github.RepoSenderGetter, prNumber int, opts *github0.ListOptions) ([]*github0.PullRequestReview, *github0.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReviews", ctx, webhook, prNumber, opts)
	ret0, _ := ret[0].([]*github0.PullRequestReview)
	ret1, _ := ret[1].(*github0.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListReviews indicates an expected call of ListReviews.
func (mr *MockClientMockRecorder) ListReviews(ctx, webhook, prNumber, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReviews", reflect.TypeOf((*MockClient)(nil).ListReviews), ctx, webhook, prNumber, opts)
}

// ListTeamMembers mocks base method.
func (m *MockClient) ListTeamMembers(ctx context.Context, webhook github.RepoSenderGetter, teamSlug string, opts *github0.TeamListTeamMembersOptions) ([]*github0.User, *github0.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTeamMembers", ctx, webhook, teamSlug, opts)
	ret0, _ := ret[0].([]*github0.User)
	ret1, _ := ret[1].(*github0.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTeamMembers indicates an expected call of ListTeamMembers.
func (mr *MockClientMockRecorder) ListTeamMembers(ctx, webhook, teamSlug, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTeamMembers", reflect.TypeOf((*MockClient)(nil).ListTeamMembers), ctx, webhook, teamSlug, opts)
}

// MergePR mocks base method.
func (m *MockClient) MergePR(ctx context.Context, webhook github.RepoSenderGetter, prNumber int, commitMsg string, opts *github0.PullRequestOptions) (*github0.PullRequestMergeResult, *github0.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergePR", ctx, webhook, prNumber, commitMsg, opts)
	ret0, _ := ret[0].(*github0.PullRequestMergeResult)
	ret1, _ := ret[1].(*github0.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// MergePR indicates an expected call of MergePR.
func (mr *MockClientMockRecorder) MergePR(ctx, webhook, prNumber, commitMsg, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergePR", reflect.TypeOf((*MockClient)(nil).MergePR), ctx, webhook, prNumber, commitMsg, opts)
}

// PR mocks base method.
func (m *MockClient) PR(ctx context.Context, webhook github.RepoSenderGetter, number int) (*github0.PullRequest, *github0.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PR", ctx, webhook, number)
	ret0, _ := ret[0].(*github0.PullRequest)
	ret1, _ := ret[1].(*github0.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// PR indicates an expected call of PR.
func (mr *MockClientMockRecorder) PR(ctx, webhook, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PR", reflect.TypeOf((*MockClient)(nil).PR), ctx, webhook, number)
}

// RemovePRLabel mocks base method.
func (m *MockClient) RemovePRLabel(ctx context.Context, webhook github.RepoSenderGetter, prNumber int, label string) (*github0.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePRLabel", ctx, webhook, prNumber, label)
	ret0, _ := ret[0].(*github0.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemovePRLabel indicates an expected call of RemovePRLabel.
func (mr *MockClientMockRecorder) RemovePRLabel(ctx, webhook, prNumber, label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePRLabel", reflect.TypeOf((*MockClient)(nil).RemovePRLabel), ctx, webhook, prNumber, label)
}

// RequestReviewers mocks base method.
func (m *MockClient) RequestReviewers(ctx context.Context, webhook github.RepoSenderGetter, prNumber int, reviewers []string) (*github0.PullRequest, *github0.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestReviewers", ctx, webhook, prNumber, reviewers)
	ret0, _ := ret[0].(*github0.PullRequest)
	ret1, _ := ret[1].(*github0.Response)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RequestReviewers indicates an expected call of RequestReviewers.
func (mr *MockClientMockRecorder) RequestReviewers(ctx, webhook, prNumber, reviewers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestReviewers", reflect.TypeOf((*MockClient)(nil).RequestReviewers), ctx, webhook, prNumber, reviewers)
}
