// Code generated by MockGen. DO NOT EDIT.
// Source: standup.go
//
// Generated by this command:
//
//	mockgen --source=standup.go --destination=mock/mock.go --package mock_standup
//

// Package mock_standup is a generated GoMock package.
package mock_standup

import (
	context "context"
	reflect "reflect"

	standup "github.com/Flashgap/marvin/internal/service/standup"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Remind mocks base method.
func (m *MockService) Remind(ctx context.Context) (*standup.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remind", ctx)
	ret0, _ := ret[0].(*standup.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Remind indicates an expected call of Remind.
func (mr *MockServiceMockRecorder) Remind(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remind", reflect.TypeOf((*MockService)(nil).Remind), ctx)
}
