// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen --source=client.go --destination=mock/mock.go --package mock_jira
//

// Package mock_jira is a generated GoMock package.
package mock_jira

import (
	context "context"
	reflect "reflect"

	jira "github.com/Flashgap/marvin/pkg/jira"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AddIssueWorklog mocks base method.
func (m *MockClient) AddIssueWorklog(ctx context.Context, issueID string, hoursSpent float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddIssueWorklog", ctx, issueID, hoursSpent)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddIssueWorklog indicates an expected call of AddIssueWorklog.
func (mr *MockClientMockRecorder) AddIssueWorklog(ctx, issueID, hoursSpent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddIssueWorklog", reflect.TypeOf((*MockClient)(nil).AddIssueWorklog), ctx, issueID, hoursSpent)
}

// CreateIssue mocks base method.
func (m *MockClient) CreateIssue(ctx context.Context, payload map[string]any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateIssue", ctx, payload)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateIssue indicates an expected call of CreateIssue.
func (mr *MockClientMockRecorder) CreateIssue(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateIssue", reflect.TypeOf((*MockClient)(nil).CreateIssue), ctx, payload)
}

// SearchIssue mocks base method.
func (m *MockClient) SearchIssue(ctx context.Context, projectName, summarySearchString string) (*jira.SearchResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchIssue", ctx, projectName, summarySearchString)
	ret0, _ := ret[0].(*jira.SearchResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchIssue indicates an expected call of SearchIssue.
func (mr *MockClientMockRecorder) SearchIssue(ctx, projectName, summarySearchString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchIssue", reflect.TypeOf((*MockClient)(nil).SearchIssue), ctx, projectName, summarySearchString)
}

// TransitionIssue mocks base method.
func (m *MockClient) TransitionIssue(ctx context.Context, issueID, transitionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransitionIssue", ctx, issueID, transitionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// TransitionIssue indicates an expected call of TransitionIssue.
func (mr *MockClientMockRecorder) TransitionIssue(ctx, issueID, transitionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransitionIssue", reflect.TypeOf((*MockClient)(nil).TransitionIssue), ctx, issueID, transitionID)
}
