// Code generated by MockGen. DO NOT EDIT.
// Source: reviewload.go
//
// Generated by this command:
//
//	mockgen --source=reviewload.go --destination=mock/mock.go --package mock_reviewload
//

// Package mock_reviewload is a generated GoMock package.
package mock_reviewload

import (
	context "context"
	reflect "reflect"

	reviewload "github.com/Flashgap/marvin/internal/service/reviewload"
	github "github.com/Flashgap/marvin/pkg/github"
	github0 "github.com/google/go-github/v90/github"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Rank mocks base method.
func (m *MockService) Rank(ctx context.Context, webhook github.RepoSenderGetter, members []string) ([]reviewload.Reviewer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rank", ctx, webhook, members)
	ret0, _ := ret[0].([]reviewload.Reviewer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Rank indicates an expected call of Rank.
func (mr *MockServiceMockRecorder) Rank(ctx, webhook, members any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rank", reflect.TypeOf((*MockService)(nil).Rank), ctx, webhook, members)
}

// RepoReviewLoad mocks base method.
func (m *MockService) RepoReviewLoad(ctx context.Context, name string) (*github0.Repository, []reviewload.Reviewer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RepoReviewLoad", ctx, name)
	ret0, _ := ret[0].(*github0.Repository)
	ret1, _ := ret[1].([]reviewload.Reviewer)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// RepoReviewLoad indicates an expected call of RepoReviewLoad.
func (mr *MockServiceMockRecorder) RepoReviewLoad(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RepoReviewLoad", reflect.TypeOf((*MockService)(nil).RepoReviewLoad), ctx, name)
}

// ReviewLoad mocks base method.
func (m *MockService) ReviewLoad(ctx context.Context) ([]reviewload.RepositoryReviewers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReviewLoad", ctx)
	ret0, _ := ret[0].([]reviewload.RepositoryReviewers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReviewLoad indicates an expected call of ReviewLoad.
func (mr *MockServiceMockRecorder) ReviewLoad(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReviewLoad", reflect.TypeOf((*MockService)(nil).ReviewLoad), ctx)
}
