// Code generated by MockGen. DO NOT EDIT.
// Source: reviewload.go
//
// Generated by this command:
//
//	mockgen --source=reviewload.go --destination=mock/mock.go --package mock_reviewload
//

// Package mock_reviewload is a generated GoMock package.
package mock_reviewload

import (
	context "context"
	reflect "reflect"

	slack "github.com/slack-go/slack"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ReviewLoad mocks base method.
func (m *MockService) ReviewLoad(ctx context.Context, cmd slack.SlashCommand) (*slack.Msg, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReviewLoad", ctx, cmd)
	ret0, _ := ret[0].(*slack.Msg)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReviewLoad indicates an expected call of ReviewLoad.
func (mr *MockServiceMockRecorder) ReviewLoad(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReviewLoad", reflect.TypeOf((*MockService)(nil).ReviewLoad), ctx, cmd)
}
