// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen --source=service.go --destination=mock/mock.go --package mock_jira
//

// Package mock_jira is a generated GoMock package.
package mock_jira

import (
	context "context"
	reflect "reflect"

	jira "github.com/Flashgap/marvin/internal/service/jira"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// DoCapReportWorkflow mocks base method.
func (m *MockService) DoCapReportWorkflow(ctx context.Context, issue *jira.Issue, timeSpent float64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoCapReportWorkflow", ctx, issue, timeSpent)
	ret0, _ := ret[0].(error)
	return ret0
}

// DoCapReportWorkflow indicates an expected call of DoCapReportWorkflow.
func (mr *MockServiceMockRecorder) DoCapReportWorkflow(ctx, issue, timeSpent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoCapReportWorkflow", reflect.TypeOf((*MockService)(nil).DoCapReportWorkflow), ctx, issue, timeSpent)
}
