// Code generated by MockGen. DO NOT EDIT.
// Source: marvin.go
//
// Generated by this command:
//
//	mockgen --source=marvin.go --destination=mock/mock.go --package mock_marvin
//

// Package mock_marvin is a generated GoMock package.
package mock_marvin

import (
	context "context"
	reflect "reflect"

	github "github.com/google/go-github/v63/github"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// OnCheckRun mocks base method.
func (m *MockService) OnCheckRun(arg0 context.Context, arg1 *github.CheckRunEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnCheckRun", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnCheckRun indicates an expected call of OnCheckRun.
func (mr *MockServiceMockRecorder) OnCheckRun(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnCheckRun", reflect.TypeOf((*MockService)(nil).OnCheckRun), arg0, arg1)
}

// OnPullRequest mocks base method.
func (m *MockService) OnPullRequest(arg0 context.Context, arg1 *github.PullRequestEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnPullRequest", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnPullRequest indicates an expected call of OnPullRequest.
func (mr *MockServiceMockRecorder) OnPullRequest(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnPullRequest", reflect.TypeOf((*MockService)(nil).OnPullRequest), arg0, arg1)
}

// OnPullRequestReview mocks base method.
func (m *MockService) OnPullRequestReview(arg0 context.Context, arg1 *github.PullRequestReviewEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OnPullRequestReview", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// OnPullRequestReview indicates an expected call of OnPullRequestReview.
func (mr *MockServiceMockRecorder) OnPullRequestReview(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnPullRequestReview", reflect.TypeOf((*MockService)(nil).OnPullRequestReview), arg0, arg1)
}
